---
- name: Setup HTTPD on webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: Setup MySQL on dbservers
  hosts: dbservers
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.yum:
        name: mysql-server
        state: present

    - name: Start and enable mysqld service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
